In [1]:
import numpy as np
import xarray as xr
import pandas as pd

In [2]:
import sys
sys.path.append('./../Scripts')
import flux_area_integration as fai

In [3]:
import importlib as ilib
ilib.reload(fai)

<module 'flux_area_integration' from './../Scripts/flux_area_integration.py'>

In [4]:
Rayner = './../data/fco2_Rayner-C13-2018_June2018-ext3_1992-2012_monthlymean_XYT.nc'
df = xr.open_dataset(Rayner)

In [5]:
%%time

# clean_fai branch
fai.spatial_integration(df, ['Terrestrial_flux','ocean'])

CPU times: user 1.61 s, sys: 10.8 ms, total: 1.62 s
Wall time: 1.61 s


time earth_land_total south_land_total trop_land_total  \
0    1992-01-16 00:00:00         -2.43004        0.0308537        -2.17337   
1    1992-02-16 00:00:00         -4.21392         0.193971        -1.80941   
2    1992-03-16 00:00:00         -5.36311       -0.0598953        -1.23004   
3    1992-04-16 00:00:00        -0.104166         0.489597        0.373112   
4    1992-05-16 00:00:00          2.10811         0.288599         1.82676   
5    1992-06-16 00:00:00         -2.74327         -0.30694       -0.852089   
6    1992-07-16 00:00:00         -8.20888         0.938441        -3.66574   
7    1992-08-16 00:00:00         -5.02205          1.16353        -2.93622   
8    1992-09-16 00:00:00         -2.61683          1.15009        0.135258   
9    1992-10-16 00:00:00          0.94107         0.171594        0.563284   
10   1992-11-16 00:00:00         -1.63412        -0.270905        0.299465   
11   1992-12-16 00:00:00        -0.160414         -1.09822       -0.269238   
12   1993-01-16 00:00:00         -4.45158         -1.41169        -2.17839   
13   1993-02-16 00:00:00         -8.95834         -1.15978        -3.77888   
14   1993-03-16 00:00:00         -6.12057        -0.845827         -2.1765   
15   1993-04-16 00:00:00         -1.35014        -0.434485        0.555642   
16   1993-05-16 00:00:00        -0.821962        -0.546863         1.68064   
17   1993-06-16 00:00:00         -1.22426        -0.293444        0.399136   
18   1993-07-16 00:00:00         -9.39697        -0.243236        -3.12127   
19   1993-08-16 00:00:00         -8.00811        -0.496081        -4.13496   
20   1993-09-16 00:00:00         -4.38575        -0.310652        0.699445   
21   1993-10-16 00:00:00           2.5803         0.338082         4.42903   
22   1993-11-16 00:00:00          3.77584         0.658515          3.3729   
23   1993-12-16 00:00:00          -2.0447         0.281783        -0.30209   
24   1994-01-16 00:00:00         -1.63932         0.411662         -1.8303   
25   1994-02-16 00:00:00         -6.42955       -0.0519591        -2.45362   
26   1994-03-16 00:00:00         -4.48999        -0.685622        -1.39585   
27   1994-04-16 00:00:00         -1.36513        -0.219502        0.685649   
28   1994-05-16 00:00:00          1.00843       -0.0106041         2.05265   
29   1994-06-16 00:00:00          1.03806         0.276042        0.360182   
..                   ...              ...              ...             ...   
222  2010-07-16 00:00:00         -7.03821       0.00874109        -3.11047   
223  2010-08-16 00:00:00         -2.92928        -0.303575        -1.63635   
224  2010-09-16 00:00:00         -3.30332        -0.179673         1.86286   
225  2010-10-16 00:00:00          2.93407         0.474066         5.69767   
226  2010-11-16 00:00:00          2.54657         0.812614         2.34349   
227  2010-12-16 00:00:00        -0.877035         0.144536        0.590414   
228  2011-01-16 00:00:00         -7.16342        -0.743244        -6.66515   
229  2011-02-16 00:00:00         -12.5666          -1.2606        -7.24574   
230  2011-03-16 00:00:00         -10.6036         -1.47858         -5.0133   
231  2011-04-16 00:00:00         -4.09672        -0.925555       -0.146125   
232  2011-05-16 00:00:00          2.24905        -0.755313         4.26324   
233  2011-06-16 00:00:00         -2.39421        -0.886546         3.46809   
234  2011-07-16 00:00:00         -7.39382        -0.965725        0.163929   
235  2011-08-16 00:00:00         -7.53474         -1.07328        -1.97912   
236  2011-09-16 00:00:00         -4.48361        -0.487679        0.102827   
237  2011-10-16 00:00:00          1.87822        -0.253547         3.60403   
238  2011-11-16 00:00:00           1.9307           0.2546        0.883621   
239  2011-12-16 00:00:00        -0.690555        -0.131929         1.54561   
240  2012-01-16 00:00:00         -1.70395        -0.248836       -0.236023   
241  2012-02-16 00:00:00         -4.22173 

In [ ]:
%%time

# master_branch
fai.spatial_integration(df, ['Terrestrial_flux','ocean'])

In [5]:
lat = df.latitude
lon = df.longitude

In [6]:
df['ocean'].sel(time=df.time[0])

<xarray.DataArray 'ocean' (latitude: 180, longitude: 360)>
array([[0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.      , 0.      , 0.      ],
       ...,
       [1.256956, 1.256956, 1.256956, ..., 1.256956, 1.256956, 1.256956],
       [1.256957, 1.256957, 1.256957, ..., 1.256957, 1.256957, 1.256957],
       [1.256962, 1.256962, 1.256962, ..., 1.256962, 1.256962, 1.256962]],
      dtype=float32)
Coordinates:
  * longitude  (longitude) float64 -179.5 -178.5 -177.5 ... 177.5 178.5 179.5
  * latitude   (latitude) float64 -89.5 -88.5 -87.5 -86.5 ... 87.5 88.5 89.5
    time       object 1992-01-16 00:00:00
Attributes:
    title:    ocean
    units:    gC/m2/year

In [7]:
ocean = df['ocean'].sel(time=df.time[0]).values
ocean

array([[0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [1.2569561, 1.2569561, 1.2569561, ..., 1.2569561, 1.2569561,
        1.2569561],
       [1.2569572, 1.2569572, 1.2569572, ..., 1.2569572, 1.2569572,
        1.2569572],
       [1.2569623, 1.2569623, 1.2569623, ..., 1.2569623, 1.2569623,
        1.2569623]], dtype=float32)

In [8]:
eag = fai.earth_area_grid(lat, lon)
eag

array([[1.07896236e+08, 1.07896236e+08, 1.07896236e+08, ...,
        1.07896236e+08, 1.07896236e+08, 1.07896236e+08],
       [3.23655841e+08, 3.23655841e+08, 3.23655841e+08, ...,
        3.23655841e+08, 3.23655841e+08, 3.23655841e+08],
       [5.39316857e+08, 5.39316857e+08, 5.39316857e+08, ...,
        5.39316857e+08, 5.39316857e+08, 5.39316857e+08],
       ...,
       [5.39316857e+08, 5.39316857e+08, 5.39316857e+08, ...,
        5.39316857e+08, 5.39316857e+08, 5.39316857e+08],
       [3.23655841e+08, 3.23655841e+08, 3.23655841e+08, ...,
        3.23655841e+08, 3.23655841e+08, 3.23655841e+08],
       [1.07896236e+08, 1.07896236e+08, 1.07896236e+08, ...,
        1.07896236e+08, 1.07896236e+08, 1.07896236e+08]])

In [9]:
eag*ocean

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [10]:
(eag*ocean)[lat>23]

array([[3.45603863e+10, 3.45603863e+10, 3.45603863e+10, ...,
        2.27681023e+09, 2.27681023e+09, 2.27681023e+09],
       [3.42928657e+10, 3.42928657e+10, 3.42928657e+10, ...,
        2.25918634e+09, 2.25918634e+09, 2.25918634e+09],
       [3.40148938e+10, 3.40148938e+10, 3.40148938e+10, ...,
        2.24087344e+09, 2.24087344e+09, 2.24087344e+09],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [11]:
nag = fai.earth_area_grid(lat[lat>23], lon)
o = ocean[lat>23]
nag*o

array([[3.45603863e+10, 3.45603863e+10, 3.45603863e+10, ...,
        2.27681023e+09, 2.27681023e+09, 2.27681023e+09],
       [3.42928657e+10, 3.42928657e+10, 3.42928657e+10, ...,
        2.25918634e+09, 2.25918634e+09, 2.25918634e+09],
       [3.40148938e+10, 3.40148938e+10, 3.40148938e+10, ...,
        2.24087344e+09, 2.24087344e+09, 2.24087344e+09],
       ...,
       [6.77897613e+08, 6.77897613e+08, 6.77897613e+08, ...,
        6.77897613e+08, 6.77897613e+08, 6.77897613e+08],
       [4.06821530e+08, 4.06821530e+08, 4.06821530e+08, ...,
        4.06821530e+08, 4.06821530e+08, 4.06821530e+08],
       [1.35621500e+08, 1.35621500e+08, 1.35621500e+08, ...,
        1.35621500e+08, 1.35621500e+08, 1.35621500e+08]])

In [12]:
((eag*ocean)[lat>23]==nag*o)

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [13]:
lat.values

array([-89.5, -88.5, -87.5, -86.5, -85.5, -84.5, -83.5, -82.5, -81.5,
       -80.5, -79.5, -78.5, -77.5, -76.5, -75.5, -74.5, -73.5, -72.5,
       -71.5, -70.5, -69.5, -68.5, -67.5, -66.5, -65.5, -64.5, -63.5,
       -62.5, -61.5, -60.5, -59.5, -58.5, -57.5, -56.5, -55.5, -54.5,
       -53.5, -52.5, -51.5, -50.5, -49.5, -48.5, -47.5, -46.5, -45.5,
       -44.5, -43.5, -42.5, -41.5, -40.5, -39.5, -38.5, -37.5, -36.5,
       -35.5, -34.5, -33.5, -32.5, -31.5, -30.5, -29.5, -28.5, -27.5,
       -26.5, -25.5, -24.5, -23.5, -22.5, -21.5, -20.5, -19.5, -18.5,
       -17.5, -16.5, -15.5, -14.5, -13.5, -12.5, -11.5, -10.5,  -9.5,
        -8.5,  -7.5,  -6.5,  -5.5,  -4.5,  -3.5,  -2.5,  -1.5,  -0.5,
         0.5,   1.5,   2.5,   3.5,   4.5,   5.5,   6.5,   7.5,   8.5,
         9.5,  10.5,  11.5,  12.5,  13.5,  14.5,  15.5,  16.5,  17.5,
        18.5,  19.5,  20.5,  21.5,  22.5,  23.5,  24.5,  25.5,  26.5,
        27.5,  28.5,  29.5,  30.5,  31.5,  32.5,  33.5,  34.5,  35.5,
        36.5,  37.5,

In [14]:
np.arange(-179.5, 180.5)==lon.values

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [20]:
spa = fai.spatial_integration(df, ['Terrestrial_flux', 'ocean'], time=(0,24))

In [21]:
fai.year_integration(spa)

Year earth_land_total south_land_total trop_land_total north_land_total  \
0  1992         -29.4476          2.69072        -9.73824         -22.4001   
1  1993         -40.4063         -4.46368        -4.55531         -31.3873   
2  1994         -1.63932         0.411662         -1.8303        -0.220681   

  earth_ocean_total south_ocean_total trop_ocean_total north_ocean_total  
0          -3.00218           6.11725         -5.81536          -3.30407  
1           14.9359           12.9816        -0.143693           2.09792  
2           1.29074          0.194098          0.29251          0.804128

In [23]:
fai.whole_time_integration(spa)

earth_land_total    -71.493203
south_land_total     -1.361304
trop_land_total     -16.123846
north_land_total    -54.008052
earth_ocean_total    13.224412
south_ocean_total    19.292977
trop_ocean_total     -5.666548
north_ocean_total    -0.402018
dtype: float64